getwd()
setwd("D:/R ex/Coursera files/")
data <- read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings="?")
str(data)
data_with_dates <- data[data$Date %in% c("1/2/2007","2/2/2007"), ]
install.packages("lubridate")
library(lubridate)
datatime <- paste(data_with_dates$Date, data_with_dates$Time)
datatime_formatted <- parse_date_time(datatime,"dmy HMS")
png("plot3.png",width=480,height=480)
plot(x=datatime_formatted,y=data_with_dates[,7],type="l",xlab="",ylab="Energy sub metering",cex=0.5)
lines(x=datatime_formatted,y=data_with_dates[,8],type="l",col="red")
lines(x=datatime_formatted,y=data_with_dates[,9],type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"))
dev.off()
